server:
  port: 9000

# h2 in memory jdbc
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:oauth2
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
