server:
  port: 9000

spring:
  security:
    user:
      name: user
      password: password
      roles: USER
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        # https://github.com/eazybytes/springsecurity6/blob/3.3.0/section_16/authserver/src/main/java/com/eazybytes/authserver/config/ProjectSecurityConfig.java
        client:
          clientCredClient:
            registration:
              client-id: clientCredClient
              client-secret: "{noop}clientCredClient"
              client-authentication-methods:
                - client_secret_basic
                - client_secret_post
              authorization-grant-types:
                - client_credentials
              scopes:
                - openid
                - read
                - write
            token:
              access-token-format: self-contained
          introspectClient:
            registration:
              client-id: introspectClient
              client-secret: "{noop}introspectClient"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              scopes:
                - openid
                - read
                - write
            token:
              access-token-format: reference #默认
          authCodeClient:
            registration:
              client-id: authCodeClient
              client-secret: "{noop}authCodeClient"
              client-authentication-methods:
                - client_secret_basic
                - client_secret_post
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - https://oidcdebugger.com/debug
                - https://oauthdebugger.com/debug
                - http://127.0.0.1:8080/login/oauth2/code/authCodeClient
                - http://127.0.0.1:8080/authorized
              scopes:
                - openid # 用户的唯一标识
                - profile # 用户的基本信息
                - email
            require-authorization-consent: true
          pkceClient:
            registration:
              client-id: pkceClient
              client-secret: "{noop}pkceClient"
              client-authentication-methods:
                - client_secret_basic
                - none
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - https://oidcdebugger.com/debug
                - https://oauthdebugger.com/debug
                - http://127.0.0.1:8080/login/oauth2/code/authCodeClient
                - http://127.0.0.1:8080/authorized
              scopes:
                - openid
                - profile
                - email
            require-authorization-consent: true
            require-proof-key: true  #pkce
logging:
  level:
    org.springframework.security: trace