server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            provider: spring
            client-id: oidc-client
            client-secret: oidc-client
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/oidc-client
            scope: openid,profile
            client-name: Spring
        provider:
          spring:
            issuer-uri: http://localhost:9000
